spring.application.name=Banking_App

spring.datasource.url=jdbc:postgresql://localhost:5432/bankApplication
spring.datasource.username=postgres
spring.datasource.password=Sumii@pg123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true